export const types = {
  RESET_ALL_AUTH_REDUCER: 'RESET_ALL_AUTH_REDUCER',
  USER_LOGIN: 'USER_LOGIN',

  MOTHLY_REVENUE: 'MOTHLY_REVENUE',
  MOTHLY_REVENUE_JSON: 'MOTHLY_REVENUE_JSON',
  DAILY_REVENUE: 'DAILY_REVENUE',
}